package br.lucasslf.gis.swingviewer;

import br.lucasslf.gis.rs.client.MapServerProxy;
import br.lucasslf.gis.rs.client.MapServerProxyArcGIS10;
import br.lucasslf.gis.swingviewer.component.SnarfMapViewer;
import br.lucasslf.gis.swingviewer.component.query.Query;
import br.lucasslf.gis.swingviewer.component.toc.tree.TOC;
import br.lucasslf.gis.swingviewer.map.BaseTiledMapService;
import br.lucasslf.gis.swingviewer.map.DynamicMapService;
import br.lucasslf.gis.swingviewer.map.ImageService;
import br.lucasslf.gis.swingviewer.map.MapService;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JSlider;
import javax.swing.WindowConstants;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ELProperty;

/**
 *
 * Classe MainFrame
 */
public class MainFrame extends javax.swing.JFrame {

    private MainFrameModel model = new MainFrameModel();
    private TOC toc;

    /**
     * Construtor
     */
    public MainFrame() {

        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setBounds(200, 200, 800, 700);
        ComponentAdapter componentListener = new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                super.componentResized(e);
                snarfMapViewer2.setSize(e.getComponent().getSize());
            }
        };


        jLayeredPane1.addComponentListener(componentListener);

        String coordinateSystemCode = "102100";
        MapServerProxy service = new MapServerProxyArcGIS10();
        List<DynamicMapService> servidores = new ArrayList<DynamicMapService>();


        
        servidores.add(new MapService("http://services.nationalmap.gov/arcgis/rest/services/govunits/MapServer", 1f, "Govunits", service, coordinateSystemCode));
        snarfMapViewer2.setBaseTiledMapService(new BaseTiledMapService("http://services.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer", 1.0f, "NatGeo_World_Map", service));
        snarfMapViewer2.setCoordinateSystemCode(coordinateSystemCode);
        snarfMapViewer2.setOperationalLayers(servidores);
        snarfMapViewer2.setSize(jLayeredPane1.getSize());
        this.addKeyListener(snarfMapViewer2.getKeyListeners()[0]);

        snarfMapViewer2.setZoomSlider(jSlider1);
        jLayeredPane1.addKeyListener(snarfMapViewer2.getKeyListeners()[0]);
        toc = new TOC(snarfMapViewer2);
        
        Query q = new Query(snarfMapViewer2);

    }

    public MainFrameModel getModel() {
        return model;
    }

    public void setModel(MainFrameModel model) {
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"})
    @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new BindingGroup();

        jLayeredPane1 = new JLayeredPane();
        snarfMapViewer2 = new SnarfMapViewer();
        jSlider1 = new JSlider();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBorder(BorderFactory.createLineBorder(new Color(255, 204, 0)));
        jLayeredPane1.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        snarfMapViewer2.setEagerLoad(true);
        snarfMapViewer2.setName("snarfMapViewer2"); // NOI18N

        Binding binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.position}"), snarfMapViewer2, BeanProperty.create("cursorPosition"));
        bindingGroup.addBinding(binding);
        binding = Bindings.createAutoBinding(UpdateStrategy.READ_WRITE, this, ELProperty.create("${model.message}"), snarfMapViewer2, BeanProperty.create("message"));
        bindingGroup.addBinding(binding);

        GroupLayout snarfMapViewer2Layout = new GroupLayout(snarfMapViewer2);
        snarfMapViewer2.setLayout(snarfMapViewer2Layout);
        snarfMapViewer2Layout.setHorizontalGroup(
            snarfMapViewer2Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        snarfMapViewer2Layout.setVerticalGroup(
            snarfMapViewer2Layout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        snarfMapViewer2.setBounds(0, 0, 930, 600);
        jLayeredPane1.add(snarfMapViewer2, JLayeredPane.DEFAULT_LAYER);

        jSlider1.setOrientation(JSlider.VERTICAL);
        jSlider1.setName("jSlider1"); // NOI18N
        jSlider1.setOpaque(false);
        jSlider1.setBounds(25, 15, 25, 200);
        jLayeredPane1.add(jSlider1, JLayeredPane.DRAG_LAYER);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLayeredPane1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addComponent(jLayeredPane1, GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON
    // Variables declaration - do not modify//GEN-BEGIN:variables
    JLayeredPane jLayeredPane1;
    private JSlider jSlider1;
    SnarfMapViewer snarfMapViewer2;
    private BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
