package br.lucasslf.gis.swingviewer.component.toc.tree;

import br.lucasslf.gis.swingviewer.component.SnarfMapViewer;
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import javax.swing.GroupLayout;
import javax.swing.JScrollPane;

/**
 *
 */
public class TOC extends javax.swing.JFrame {

    /** 
     * Construtor padrão.
     */
    public TOC(SnarfMapViewer mapViewer ) {
        initComponents();
        this.setSize(400, 500);
        
        tOCTree1 = new TOCTree(mapViewer);
        jScrollPane1.setViewportView(tOCTree1);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "PMD"}) @SuppressFBWarnings
    //CHECKSTYLE:OFF
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();
        tOCTree1 = new TOCTree();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tOCTree1.setName("tOCTree1"); // NOI18N
        jScrollPane1.setViewportView(tOCTree1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //CHECKSTYLE:ON

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JScrollPane jScrollPane1;
    TOCTree tOCTree1;
    // End of variables declaration//GEN-END:variables

}
